## Fishery-Dependent Data

### Commercial - NUY

#### Landings

The systems along the U.S. West Coast for monitoring commercial fishery landings in the past did not keep track of the landings of individual rockfish species, largely because many rockfish species have similar market characteristics and therefore were landed as an unsorted mix of species.  Black rockfish in particular, which are a nearshore species and much less abundant than many of the offshore rockfish species, were generally landed in mixed-species categories.  As a consequence, the historical records do not provide a detailed accounting of the landings of black rockfish.  The basic approach taken to develop the landings series in this assessment (as in past assessments) was to apply values for the proportion of black rockfish sampled in mixed-rockfish landings.  Data on the proportions of black rockfish are sparse, with the consequence that the landings reconstructions are highly uncertain.

Commercial landings data for the modern era (1981 to present) are taken from the Pacific Fishery Information system (PacFIN), which is a central repository for U.S. West Coast groundfish landings and auxiliary information collected by the three state fishery agencies and other agencies.  A description of basic state data collection systems and overview of PacFIN is provided in Sampson and Crone (1997).  Updated dockside sampling protocols and data processing procedures for Washington are described in Tsou et al. [-@tsou_etal_2015] and Tsou and Weyland [-@tsou_weyland_2015].  A variety of sources were used to reconstruct regional landings histories for years earlier than 1981. Comparisons of the commercial catch in each fishery for the current and previous assessments Figure 81.


##### The PacFIN Era: 1981 to 2014

The PacFIN system provides estimates of commercial fishery rockfish landings by species for those strata (year, quarter, port, area, gear type, condition [alive or dead], and market category) that have species composition data available to apportion the landings to species.  For the commercial fisheries in California the source of the information provided to PacFIN is the CalCOM database, which is the repository for commercial groundfish market sample data managed by the California Cooperative Groundfish Survey (Pearson et al. 2008).  In either system, when no species composition data are available, the system reports the landings as the nominal species or as the mixed-species category that it was sold as (e.g., small rockfish), depending on how the landings were originally reported.  The amount of unspecified rockfish that cannot be apportioned to species varies by year, area, and gear type.  In many instances the landings of unspecified rockfish reported by PacFIN are quite substantial.

Although the separate geographic assessments by state region would ideally have strict geographic separation of landed catch to the location of capture, this is not possible to accomplish because information on the fishing location is generally unavailable.  Until recently logbooks that report area of capture were only available for landings by the groundfish trawl fleet.  Oregon has required a logbook for commercial vessels participating in its nearshore fishery since 2004.  At the same nearshore stock assessment workshop [@pfmc_safe_2015] it was agreed that catch histories for black rockfish stocks should be assembled on the basis of port of landing rather than location of fish capture, based on the assumption that neighboring state would catch approximately equal amounts from off each other's waters.  The one exception to this "port-of-landing equals the state-of-capture rule" is for trawl-caught fish landed at Astoria, OR, the vast majority of which were caught in waters off Washington.

Staff from the Oregon Department of Fish and Wildlife (ODFW) used species composition samples collected during 1976 to 1993 to conduct an analysis of the spatial distribution of black rockfish landed at Astoria, OR.  Astoria is the northernmost port in Oregon and is located near the mouth of the Columbia River, which forms the boundary between Oregon and Washington.  The aggregate proportion of black rockfish expanded pounds that were taken north of the Columbia River (i.e., from waters off Washington) was 98.6%.  This percentage was applied to all historical trawl landings of rockfish at Oregon's Columbia River District ports prior to 1976.vNon-trawl landings into Astoria were assumed to have been caught from Oregon waters.  

Starting in 1994 black rockfish landed into Oregon were legally required to be sorted and sold in a separate black rockfish market category and were also reported as separate retained catches in the mandatory trawl logbooks.  Based on the retained catches reported in the logbooks, the estimated proportion of the trawl-caught black rockfish that were caught from off Washington and landed into Astoria ranged from 65 to 100 percent. These black rockfish are accounted for in the Washington regional assessment (Table 48).

The Washington Department of Fish and Wildlife (WDFW) provided commercial fishery landings based on fish ticket records of black rockfish harvested off Oregon by vessels landing at ports in Washington.  Landings were less than 1 mt per year for the period 1971 to 2014; therefore, all landings to Washington ports were assumed to occur in waters off Washington in this assessment.

The landings data series for black rockfish landed in California, Oregon, and Washington during 1981 to 2014 were assembled from three PacFIN or CalCOM data sets.  The first data set consisted of direct estimates of black rockfish landings by state (described as BLCK in PacFIN), which the systems derived from fish tickets, species composition estimates, and trawl-logbooks provided by the California Department of Fish and Wildlife (CDFW), the ODFW, and the Washington Department of Fish and Wildlife (WDFW).  The second data set consisted of landings of black rockfish that were nominally landed in the black rockfish market category (described as BLK1 in PacFIN) but no direct species composition samples were available to confirm their purity.  Prior to 1993, there was no sorting requirement in the states and no explicit market category for black rockfish, which were landed in a mixed-species rockfish category.  Starting in 1994, black rockfish landed in Oregon were legally required to be landed and sorted into a separate black rockfish market category.  Similar sorting requirements were implemented in 2001 in California and in 2006 in Washington.  

The third PacFIN data set (URCK in PacFIN) was derived from landings of rockfish for which species composition sample estimates were unavailable, but which might feasibly contain some black rockfish.  This derivation involved applying estimates of the percentages of black rockfish (%Black) to the landings of unspecified rockfish.

For each regional assessment the final values for annual commercial landings of black rockfish were the sum of the original PacFIN estimates, to which were added the nominal landings of black rockfish (listed as black rockfish on fish tickets but not verified by sampling) and the estimates of black rockfish in the unspecified rockfish landings.

The landings series during the PacFIN era are quite erratic, sometimes exhibiting large variations between years.  While these changes could be a true reflection of changing fishing patterns, they may be no more than artifacts of low levels of species composition sampling.  A study of the groundfish landings estimates for California [@pearson_etal_2008] evaluated the reliability of species composition sampling for various rockfish species.  The study noted that black rockfish are readily misidentified as blue rockfish, that the hook-and-line fishery in California was not well sampled until the 1990s, and that many of the California landings estimates are based on "borrowed" data or by treating the black rockfish market category as "pure".


##### Oregon Commercial Fishery Landings: 1892 to 2014 

The commercial fishery landings data series for Oregon (Table 25) were assembled from four primary sources: 1) PacFIN, as described above; 2) Pacific Marine Fisheries Commission (PMFC) landings data series for 1956 to 1980; 3)Fishery Statistics of the U.S. for 1927 to 1955; and (4) ODFW's Ocean Recreational Boat Survey for 1979 to 2014 (provided by P. Mirick, ODFW).  Details regarding the PMFC and Fishery Statistics of the U.S. data series are provided in the 2007 assessment document.

Much of the information underlying the commercial catch reconstruction was assembled from primary sources described above in a database documented in Karnowski et al. [-@karnowski_historical_2014]. Careful review of the Karnowski et al. database uncovered some unusual features in the species composition information that underlies the landings reconstruction. For example, during the period 1963 to 1975 the annual %Black values used in the Karnowski et al. [-@karnowski_historical_2014] database varied from 0% to 100%, and produced very erratic year-to-year variations in the landings of black rockfish. 

Staff from ODFW recommended using an alternative reconstruction of historic landings that was based on a fixed set of PMFC-area specific %Black values for the time period 1949 to 1975 (2.2% for area 2A, 4.5% for 2B, 4.4% for 2C, and 14.1% for 3A). There were similar issues with high variability in the %Black values used in the Karnowski et al. database for the period 1976 to 1986. For this period staff from ODFW recommended an alternative reconstruction of historic landings based on the following fixed set of PMFC-area specific %Black values: 0.77% for area 2A, 0.29% for 2B, 0.54% for 2C, and 6.82% for 3A.


#### Foreign Fishery Catches of Black Rockfish - NUY

Rogers [-@rogers_species_2003] developed catch reconstructions for removals by foreign trawlers operating off the U.S. West Coast during the late 1960s to mid-1970s. Although this study reports that Japanese vessels operating in the Columbia and Eureka statistical areas (Oregon and northern California) caught substantial amounts of black rockfish, with cumulative catches of more than 500 mt over 10 years, it seems very unlikely that foreign vessels could have operated sufficiently close to shore to catch appreciable amounts of black rockfish. This assessment does not include Rogers' estimates of foreign fleet removals of black rockfish. 


### Recreational Removals

Comparisons of the catch in each recreational fishery for the current and previous assessments are in Figure 81.


#### Historic Ocean Boat Landings and Discards (1973 - 2000)

Recently, the Oregon Department of Fish and Wildlife (ODFW) undertook an effort to comprehensively reconstruct all marine fish recreational ocean boat landings prior to 2001 (Whitman 2023, in review).  Reconstructed catch estimates from the Oregon Recreational Boat Survey (ORBS) improve upon estimates from the federal Marine Recreational Fisheries Statistical Survey (MRFSS), which have known biases related to effort estimation and sampling (Van Voorhees et al. 2000) that resulted in catch estimates considered implausible by ODFW.  However, the ORBS sample estimates are known to lack the comprehensive spatial and temporal coverage of MRFSS.  Addressing this coverage issue is a major part of this reconstruction. In general, the base data and methodology for these reconstructed estimates are consistent with recent assessments for other nearshore species (Cope and Whitman 2021; Langseth et al. 2021; Taylor et al. 2021; Wetzel et al. 2021).  

Prior to 2001, ORBS monitored marine species in both multi-species categories, such as rockfish, flatfish, and other miscellaneous fishes, and as individual species, such as lingcod or halibut.  For this comprehensive reconstruction, four species categories were selected to reconstruct, including rockfish, lingcod, flatfish and miscellaneous, which constitute the bulk of the managed marine fish species.  Black rockfish are a component of the rockfish species category.  

Category-level estimates were expanded to account for gaps in sampling coverage in two separate pathways. First, estimates from five major ports were expanded to include unsampled winter months in years lacking complete coverage.  Expansions were based on available year-round sampling data and excluded years where regulations may have impacted the temporal distribution of catch.  Second, all other minor port estimates were expanded to include seasonal estimates in years lacking any sampling based on the amount of minor port catch as compared to all major port estimates.  A subset of landings were sampled by ORBS for species compositions within these categories.  Once category-level landings were comprehensive in space and time, species compositions were applied for the three multi-species categories, including rockfish, flatfish and miscellaneous fish.  Borrowing rules for species compositions were specific to the category and determined based on a series of regression tree analyses that detailed the importance of each domain (year, month, port and fishing mode) to variability in compositions.  

Ocean boat estimates from 1979 – 2000 in numbers of fish of black rockfish from the above described methods were converted to biomass using biological samples from MRFSS (pers. comm. A. Whitman, ODFW).  MRFSS biological data are available from 1980 – 1989 and 1993 – 2000. An annual average weight was applied to the total annual number of fish to obtain an annual biomass estimate of the landings. Several years missing biological data (1979, 1990 – 1992) were filled in using neighboring years or interpolation. These landings in biomass were provided by ODFW and do not include an estimate of discarded fish. Landings during this time period average 309.9 mt and are of similar magnitude to the previous assessment (Cope et al. 2015). Landings from 1973 to 1978 were initiated at zero in 1973 and ramped up to the initial biomass estimate from 1979. Bag limits in the recreational fishery during this time period (prior to 2001) are generally liberal and ODFW staff recommended that no additional mortality of discarded fish be included. 

#### Modern Ocean Boat Landings and Discards (2001 - 2022) 

Recreational landings for ocean boat modes from 2001 – 2022 are available from RecFIN.  Both retained and released estimates of mortality are included, though retained mortality contributes the vast majority to total mortality.  Release mortality is estimated from angler-reported release rates and the application of discard mortality rates from the PFMC. The average proportion of black rockfish discarded was 0.92% from 2001 – 2022. From 2001 – 2022, total landings averaged 307.6mt, ranging from 198.7 to 458.6 mt. In 2022, estimated ocean boat landings were 374.3 mt. 

#### Shore and Estuary Boat Landings (1892 - 2022) 

ODFW provided reconstructed estimates of shore and estuary landings for black rockfish from 1892 – 2022, using methodology similar to recent assessments (Taylor et al. 2021; Langseth et al. 2021; Wetzel et al. 2021).  Data sources include MRFSS and the Oregon Shore and Estuary Boat Survey (SEBS).  Numbers of fish were provided by MRFSS from 1980 – 1989 and 1993 – June 2003, and by SEBS from July 2003 – June 2005.  An annual mode-specific average weight was applied to numbers of black rockfish from 1980 – 1989 and 1993 – 2005.  Separate weights were calculated for shore and estuary boat modes, and excluded extreme outliers and imputed values.  This reconstruction also applied two scaling factors to remove bias towards freshwater sampling and underestimation of estuary boats, as detailed in Dick et al. (2018).  To estimate black rockfish landings from July – December 2005, an expansion was developed using the three year average of the ratio between the first six months of the year and the total annual landings from MRFSS and SEBS landings from 2002 - 2004.  Separate expansions were developed for shore mode and estuary boat modes.  

Unlike the ocean boat recreational fishery, which developed during the 1970s, it was assumed that some shore and estuary fishing for black rockfish has occurred for many decades. As a result, the previous black rockfish assessment used fishing licenses to scale shore and estuary landings (Cope et al. 2015). However, the link of black rockfish landings to fishing license sales is not well supported (pers. comm. A. Whitman, ODFW) and this assessment assumes a simple linear ramp from zero catch in 1892 to the estimated shore/estuary biomass of 28.1 mt in 1980, which produces a similar trajectory in catches. Additionally, the ODFW does not currently sample shore and estuary boat fishing trips, and so a ten year average landing (1996 – 2005; 13.3 mt/year) was used to estimate shore and estuary boat landings during 2006 – 2022. Again, this methodology differed from the previous assessment and did not use fishing license sales to scale the removals but still produces a similar trajectory and magnitude of removals as the 2015 assessment shore/estuary removals.  Shore and estuary boat landings for black rockfish were minor compared to recreational ocean boat removals but consistent. Shore and estuary boat landings average 17.2 mt annually from 1980 – 2003.  To obtain an estimate of discarded fish for the shore and estuary fleet, the ocean boat proportion of discarded fish from RecFIN (0.92%; 2001 – 2022) was applied to the estimated shore and estuary landings during 2001 – 2022. As with the ocean boat fleet, discard mortality was not estimated for shore and estuary landings prior to 2001, as bag limits were relatively high and discarding was assumed to be very limited. 

#### Alternate Historical Catch Series - NOT UPDATED

The exploration of alternative removal histories was limited before, during and after the STAR panel. After consulting with state representatives it was apparent that more formal catch history reconstructions with the intent on characterizing stanzas of catch uncertainty is generally needed to specify alternative catch histories that reflect the underlying uncertainty in the catch reconstructions. Sensitivities to 50% and 150% catch times series, as well as using the former catch history in the Washington model were explore and demonstrated little sensitivity to such changes. More work in the future is thus needed to formalize either alternative catch series or explicitly incorporating catch uncertainty into model specification.

### Estimated Discards - NEED TO UPDATE COMMERCIAL PARAGRAPH

In the previous assessment, commercial discards were not accounted for due to the information provided by the West Coast Groundfish Observer Program (WCGOP) at that time, showing about a 1% discard rate in their survey.  We evaluated the WCGOP estimates of black rockfish discards from 2002-2013, which showed a total of 32.2 mt in estimated discards and total landings of 2042.5 mt coastwide, resulting in a rough discard rate estimate of 1.58%.  This amount of discards was included in the CA HKL non-live fishery landings, going back to 1916, and in the OR HKL non-live fishery landings to 1892. Given the minimal amount of discards, no further depth-dependent mortality estimates were evaluated for Oregon and California and this discard rate was added to the total commercial removals.  Parker et al [-@parker_buoyancy_2006] concluded that semi-pelagic, vertically mobile species, such as black rockfish, show less barotrauma; hence these estimates could be slightly overestimated.  

As noted above, recreational discard mortality for the ocean boat fleet was included from RecFIN from 2001 - 2022. Based on these landings data, an average discard rate of 0.92% was applied to the shore and estuary boat fleet to account for discarded fish from 2001 - 2022. No recreational discards were accounted for prior to 2001, based on ODFW recommendation that bag limits for black rockfish were high and discards were likely extremely low. There are no data that can speak to discard rates in the recreational fishery prior to 2001. 

## Size and Age Composition Data - NUY

Fish length measurements, from both the commercial and recreational fishery, are one of the major sources of data for this assessment.  Length composition data from the commercial and recreational fisheries in Oregon were included, as were age composition data from the commercial and recreational fisheries in Oregon.

A large proportion of the length composition data were from the Marine Recreational Fishery Statistics Survey (MRFSS), which is a federally funded program operating since 1980 that collects information on the marine sport fisheries.  The MRFSS program includes an intercept survey in which sport anglers are interviewed as they return from fishing trips, and where samplers can identify and measure the retained catches.  The MRFSS sampling is intended to cover all forms of marine recreational fishing, including shore-based activities from beaches, jetties, and piers.  In contrast the ORBS program that operates only in Oregon interviews and samples anglers operating from boats.  The MRFSS length data, which are housed in the RecFIN database, generally do not indicate the sex of individual fish that were measured.  Similarly, the length data collected by the ORBS program does not generally indicate gender.  In Oregon, a separate and independent sampling program from ORBS, the Marine Non-Salmonid Recreational Fishery Study (MNSRFS), collects length, age and gender data from recreational anglers operating from boats.  The length and age data collected by the MNSRFS program are the only recreational data used in the assessment where gender is recorded.


### Length and Age Sample Sizes - NUY

The level of commercial fishery sampling for black rockfish has been erratic, with almost no samples taken in Oregon until the early 1990s (Figure 80).  In California there was a shift from trawl to non-trawl samples, which in part reflects the growing importance of hook-and-line fishing in the nearshore areas and the development of a live-fish fishery.  Sampling of the recreational fisheries in Oregon and California by the MRFSS program has been reasonably consistent except for the hiatus during 1990-92 when the program was not funded.  The standard MRFSS sampling program stopped in 2003 in Oregon and in 2004 in California, around which time the states assumed larger roles in sampling their recreational fisheries.  This resulted in some loss of continuity in the sampling processes.


#### Multinomial Sample Sizes - NUY

Initial input values for the multinomial samples sizes determine the relative weights applied in fitting the annual composition data within the set of observations for each fishery.  The initial input values in this assessment were based on the following equation developed by I. Stewart and S. Miller (NWFSC), and presented at the 2006 Stock Assessment Data and Modeling workshop.
Neff = Ntrips + 0.138 * Nfish if Nfish/Ntrips < 44
Neff = 7.06 * Ntrips if Nfish/Ntrips ? 44

Tuning of the assessment model involved multiplying the input sample sizes for each fishery by an adjustment factor to achieve a better balance between how well the model fit the set of composition data and how well it should have fit the data given the sample sizes underlying the data.


#### Length Compositions - NUY

The length data for the assessment model were tabulated into 2-cm length bins ranging from 10 cm to 64 cm, with accumulator bins at each end. 

The length composition data indicate some general differences between the three fishery types, with the trawl fisheries producing the largest fish, the recreational fisheries producing the smallest fish, and the non-trawl fisheries producing fish of intermediate length.  There is little evidence in any of the length composition data of distinct modes or successions of modes from one year to the next that might represent strong year-classes.

The recreational fishery length composition data from Oregon are generally quite symmetrically distributed, whereas the recreational fishery length composition data from California are often quite asymmetric, with an extended shoulder having modest numbers of large fish.   However, the data for the first few years of the California series are similar in general shape to the Oregon recreational length composition data.

Sample length composition data from the California sport fishery for 1999 and 2000 were excluded from the assessment model because they had very narrow distributions and were extremely different from adjacent years.  Close examination of the raw data did not indicate any obvious reason for the odd appearance of these length compositions.


##### Oregon Length Compositions

###### Commercial - NUY

The biological data for the commercial fishery were extracted from PacFIN on April 24th, 2015.  These data are from trawl and non-trawl (hook-and-line) dead and live-fish fisheries from ports south of Astoria.  The PacFIN dataset contains records for Oregon landings into Astoria; however, these are believed to have been landed in Washington waters and are used in the Washington model.  Length composition data are reported either in fork length or total length (Table 27).  Fork lengths are preferred; where they are missing the total length is used. These data are expanded to reduce the effect of non-uniform sampling effort. The expansions are by weight, catch/sampled catch; first on a per-trip level, and then on a per-year, per-fishery level.  Expansion factors have a minimum value of 1, and are capped at their 90th percentile value. The final sample size is the product of the two expansion factors, which is then capped at its 90th percentile value. The data were stratified by gender and fishery (Table 27).  The final sample sizes were stratified and summed by length bin (10 cm to 60 64 cm bins, 2 cm in width), and an effective sample size is computed from the number of trips and number of fish each stratum represents, according to the Stewart and Miller method for multinomial fishery data (See page 56). A small number of unsexed fish were present in the data; as these did not represent a distinct length distribution, they were excluded from the model.


###### Recreational

Recreational length samples were obtained from two primary sources: MRFSS and RecFIN (ORBS).  ODFW special project sampling data were considered but given the high sample sizes available from standard sampling, these data were not utilized. From 1980 – 1989 and from 1993 – 2000, the MRFSS program collected samples from both ocean and inland (estuary) areas (n = 46,656).  ODFW provided MRFSS samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values (n = 32,130).  From 1980 – 1989, total lengths (mm) were collected by MRFSS, which were converted to fork length.  From 1993 – 2000, fork length (mm) was collected.  Length samples from 2001 – 2022 from the ORBS sampling program are available on RecFIN (n = 197,216).  All ORBS samples are by fork length (mm).  The vast majority (95.5%) of these samples are from ocean trips (n = 188,372). Table X details sample sizes by year and recreational fleet.  

##### Tagging data - NUY

The Washington Department of Fish and Wildlife provided sampled length data from the tagging survey for sexed and unsexed samples for years 1981-2014 (Table 54). Unsexed and sexed data were generally available in different years. Like the recreational data, composition data were used as collected (i.e., not expanded) and effective sample sizes were based on unique "sequence" sizes, which is roughly equivalent to a trip. 

#### Age Compositions - NUY

##### Oregon Age Compositions - NUY

The fishery data for the assessment model consisted of otolith age-readings, mostly from the recreational fishery (Table 30 to Table 32).  Age composition data were a subset of the length data, 41,212 records in total. The age composition data for the assessment model were tabulated into 1-yr age bins from 1 to 40 years.  For the data tabulation provided in this document, the accumulator bins were extended to compress and simplify display of the data.

The age composition data generally do not show much evidence of distinct year-classes that can be easily tracked from one year to the next, which suggests that that there is not much recruitment variability from year-to-year or that age-reading error is sufficient to mask the appearance of strong year-classes.
As for the length comps, the unsexed fish (139 samples) were treated as a separate dataset.  
Age-at-length compositions were not expanded; the final sample sizes were set to 1 before tallying.  For all three models, the ages were modeled as conditional age-at-length.

#### Mean weights

TBD  by ADW

### Abundance Indices - NUY

Age and length composition data by themselves do not provide sufficient information to reliably determine trends in stock abundance and biomass.  Most assessments of U.S. West Coast groundfish stocks rely on estimates of stock biomass from research trawl surveys to provide information on biomass trends, but black rockfish are very infrequently caught in any of the bottom trawl surveys, which have a limited coverage of shallow nearshore waters (none of the surveys have ever been conducted in waters shallower than 55 m).  The primary tuning indices available for these assessments are based on recreational catch-per-unit-effort (CPUE), although a series of estimates of absolute abundance, based on an ODFW tagging study, are available for a portion of the stock off Oregon.

The regional assessments for California and Oregon use an approach similar to that used in the 2007 assessment for deriving standardized indices of abundance, and uses the same basic data: dockside interview data from Marine Recreational Fisheries Statistics Survey (MRFSS Type-3 records) in both states, dockside interview data from Ocean Recreational Boat Survey (ORBS) in Oregon; and at-sea observer data from observers aboard commercial passenger fishing vessels (CPFVs) off central California and Oregon.  Dockside interview data are available for Washington from the WDFW OSP.

Given the reliance of all three regional assessments on recreational fishery CPUE data, all three assessments used similar approaches to develop their CPUE indices.  Because sport anglers target a wide variety of species, many fishing trips are very unlikely to ever encounter a black rockfish.  The lack of any catch of black rockfish on these trips provides no information on the relative abundance of black rockfish, and these trips were not included in a catch-rate analysis in these assessments.  

To restrict the sets of ORBS and MRFSS data (respectively) to trips that are likely to have encountered black rockfish, the multispecies analysis developed by Stephens and MacCall [-@stephens_multispecies_2004] was used to select a subset of the data for developing the CPUE indices.  The analysis applies a logistic regression to trip-level data on the presence or absence of the target species (black rockfish) based on presence or absence data for a suite of other species that occur with reasonable frequency in the catch and effort data set.  

The resulting logistic regression coefficients for each of the other species provide a measure of the likelihood of catching the target species, given that the other species were caught.  Positive coefficients imply a greater likelihood of catching the target species.  Separate analyses were done for the dockside MRFSS and ORBS data, and only data from ocean charter boats were used.  Data from private boats were excluded because it seemed likely that private anglers would have less consistent fishing patterns than charter boat operators, and would therefore provide noisier information. A summary of indices considered in each assessment model and general the influence each has on the base models (i.e., rank) is give in Table 5.

#### Oregon On-board Observer Programs

The onboard observer programs in Oregon collect drift-specific information at each fishing stop on an observed trip.  At each fishing stop recorded information includes start and end times, start and end location (latitude/longitude), start and end depth, number of observed anglers (a subset of the total anglers), and the catch (retained and discarded) by species of the observed anglers.  Data for the onboard observer indices used in these black rockfish assessments for the recreational CPFV fleet are from several sampling programs. 

The ODFW initiated an onboard observer program in 2001, which became a yearly sampling program in 2003 (Monk et al. 2013).  Both California and Oregon provided onboard sampling data through 2014.  Data were analyzed at the drift level and catch was taken to be the sum of observed retained and discarded fish.

We created separate indices in California for the 1987-1999 and 2000-2014 datasets due to the number of regulation changes occurring throughout the time period (see Appendix A for regulations history).  In 1987, trips were only observed in Monterey, and are therefore excluded from the analysis. 


##### Data Filtering

Prior to any analyses, preliminary data filters were applied.  Trips/drifts from the CDFW 1988-1998 meeting the following criteria were excluded from analyses:

1.	Drift associated with a fishing location code that was not assigned to a reef.
2.	Drifts identified as having possible erroneous location, observed anglers, or time data
3.	Trips encountering <50% groundfish species.
Trips/drifts from the ODFW, CDFW 1999-2014, and Cal Poly databases meeting the following criteria were excluded from analyses:
1.	ODFW halibut-targeted trips were excluded.
2.	Trips encountering <50% groundfish species. 
3.	Drifts within the current Stonewall Bank Yelloweye Rockfish Conservation Area.
4.	Drifts within Arcata Bay, Humboldt Bay, South Bay, or San Francisco Bay.
5.	Drifts missing a starting location (latitude/longitude).
6.	Drifts identified as having possible erroneous location or time data.
7.	Drifts missing both starting and ending depths.
8.	Drifts within the habitat data occurring farther than 83 m from a reef in Oregon and 34 m in California (see Appendix B for details on reef filtering).
9.	Drifts outside the habitat data in California occurring farther than 141 m from reef (see Appendix B for details on reef filtering).
10.	Drifts occurring on a reef with <3 positive encounters of black rockfish.
11.	Drifts occurring on a reef in which black rockfish was observed in <25% of years the reef was visited.


#### Oregon Commercial Fishery Indices

Only one abundance index is available from the Oregon commercial fisheries, one derived from a nearshore logbook CPUE time-series that was not long enough for use in the 2007 assessment.

##### The Nearshore Logbook Index

The ODFW has required nearshore commercial fishers (both nearshore permitted vessels and open access vessels) to submit fishing logbooks since 2004.  Compliance is generally high, averaging around 80%, but has varied through time ranging from 65% in 2007 to 95% in recent years.  Although required to provide all requested information in the logbook per fishing gear set, there has been substantial variation in the quantity and quality of information reported in logbooks.  Responses from submitted logbooks were entered into a central database and span the years 2004 through 2013.  At the time of this assessment, 2014 logbook submissions were not fully processed and thus were not available.

Logbook information went through several data quality filters to attain the most consistent and representative data set through time to estimate relative abundance trends.  Results from the filtration algorithm are summarized in Table 34. Of note, logbook submissions from black and blue rockfish-permitted vessels with and without a nearshore endorsement were included in the analysis, because these vessels consistently fish in areas where black rockfish are encountered.  

Based on advice from the July STAR panel, a filter that had previously required that a vessel fished in all 10 years (2004-2013) to be included was relaxed to requiring vessels to have fished in only three years to be included.  This increased precision, but did not change the selection of covariates in the final model.  Individual observations of catch (in kg) and effort (hook hour, or the number of hooks used multiplied by the number of hours fished) were at the trip level, where multi-set trips were aggregated to the trip level.  ODFW sets bimonthly trip landing limits for black rockfish and these have changed through time.  However, trip limits have not generally been exceeded in the subset of logbook data used for black rockfish, and thus there was no need to exclude subsequent trips.  The final subset of logbook data included 13,522 trips (60% of the full set of logbook data) from 113 vessels (Figure 84).
Preliminary data analyses identified levels or limits of filtering variables in order to preserve adequate sample sizes and representative trips for black rockfish.  For example, gear type was restricted to hook-and-line (excluding longline gear) because this method accounted for 85% of all sets.  Garibaldi, Pacific City, Port Orford, Gold Beach, and Brookings were the only ports that included a sufficient number of vessels and sets throughout the time series.  Thus, this abundance index is representative of black rockfish in the nearshore in waters adjacent to these locations (Figure 82)
Fishing depth at the start of a set was restricted to within 30 fathoms (54.9 m), which included more than 99% of all sets by permitted vessels, to ensure only CPUE in areas where black rockfish are commonly encountered was evaluated.

Covariates considered in the full model included Month, Vessel, Port, Depth, and People (Figure 85).  All covariates were specified as categorical variables, except depth was a continuous variable.  Depth was included to account for general differences in bathymetry and fishing depth restrictions associated primarily with limiting catch of yelloweye rockfish.  People were included in an attempt to control for the potential oversaturation of hooks at a given fishing location and the interaction that multi-crew trips (# fishers onboard) may have on fishing efficiency.  The selection of covariates included in final models were evaluated using standard information criterion for relative goodness of fit (AICc and BIC) in a backwards stepwise fashion, where a covariate remained in the model if model fit was improved relative to an otherwise identical model without the covariate.   

CPUE was modeled using a delta-GLM approach, where the catch occurrence (binomial) component was modeled using a logit link function and the positive catch component was modeled according to a gamma distribution with a log link function.  CPUE was calculated for each trip, where total catch was defined as the sum total of all reported retained catch (in weight) and released catch (numbers converted to weight by applying a median catch weight) and total effort was defined by hook-hours.  A lognormal distribution for the positive catch component was also evaluated, but graphical summary diagnostics of model adequacy slightly favored the gamma distribution.   A delta-GLMM was also attempted to specify vessel-year interaction effects as stemming from a distribution (random effect) and to account for this added source of variation.  However, the delta-GLM approach was preferred because runtime for the delta-GLMM jackknife procedure to estimate standard errors was restrictive; an alternative normal approximation to the delta-GLMM index standard error estimates resulted in overinflated CVs; and the resulting index time-series between the two approaches was very similar.

Model selection procedures identified the covariates Vessel, Port, and People as important for the catch occurrence (binomial) model component and Vessel, Month, Port, Depth, and People for the positive catch model component.  The categorical Year factor of interest was automatically included in each model component.  Extracted, back-transformed and bias corrected estimates of the Year effect from each model component were then combined and used for the abundance illustrated in Figure 86.  A jackknife resampling routine was conducted to estimate the standard error (and CV) of the Year effects.  The relative effects of each covariate are shown in Figure 87 for the catch occurrence component and Figure 88 for the positive catch component.  Standard model diagnostics show adequate fit and general consistency with GLM model assumptions for the positive catch component (Figure 89).


#### Oregon Recreational Indices

The four recreational fishery abundance indices available for the Oregon regional assessment are summarized in Table 35 and Figure 95.  The sections below describe the underlying data and derivations of the indices.


##### On-Board Observer CPUE for Oregon, 2001 and 2003 to 2014

The filtered dataset included 10,738 drifts, of which 6,410 (60%) drifts with positive encounters.  Only eight samples occurred in the 60-79 m depth range, and we therefore removed drifts from this depth range from the analysis.  ODFW does not sample in Wave 1 (January/February).

The selected data contained categorical variables for Year (13 levels), Wave (4 levels), two Regions (north and south of Florence), and three depth bins (Depth: 0-19 m, 20-39 m, and 40-59 m).  Model selection via AIC selected a lognormal model with Year, Wave, Depth, Region, Depth:Region, and Year:Region, while a binomial with Year, Depth, Region, and Year:Region.  There was enough data to explore a difference in the CPUE trends between regions.  The region south of Florence comprised 72% of the area where black rockfish were encountered, with the remaining 28% north of Florence.  There is no discernable difference, except for 2001, in the indices between the regions (Figure 90).  The trends between the main effects model and the area-weighted mean model are very similar (Figure 90).

In the lognormal submodel, stepwise BIC retained the Year, Depth, Region and the Depth:Region interaction, but did not include any interactions with Year. In the binomial model, stepwise BIC retained Year and Depth. The final Year effects are shown in Table 35 and Figure 95.


##### MRFSS Dockside CPUE for Oregon, 1980 to 2000

For the RecFIN data from Oregon, the logistic regression analysis to select likely black rockfish trips was based on data from 6,165 charter-boat trips and a suite of 23 species (excluding black rockfish).  The analysis generally produced large positive coefficients for shallow-water species that one would expect to co-occur with black rockfish (e.g., copper rockfish and blue rockfish), and large negative coefficients for deep-water or pelagic species that one would not expect to co-occur with black rockfish (e.g., Pacific halibut and coho salmon).  Those trips having an estimated probability of producing a black rockfish that exceeded the cut-off value of 0.758 were selected for the CPUE analysis.  

This cut-off value was chosen to balance the false-positives against the false-negatives and resulted in some trips that were estimated to be false positives, where black rockfish were caught, but should not have been, given the other species caught during those trips.  These probably represent trips that fished in multiple locations, and thus caught a mix of shallow- and deep-water species.  The screening also resulted in the inclusion of trips (false negatives) that should have caught black rockfish (given the other species), but did not.  A total of 5,261 trips were selected for the CPUE analysis.

The MRFSS dockside standardized CPUE index for Oregon (Figure 95) was developed from the selected subset of the catch and effort data using GLMs, with a binomial model to estimate the probability of catching at least one black rockfish and a gamma model to estimate the magnitude of the positive catches per angler-fishing-hour.  In all cases, the structural models had three main effects for the factors Year, Wave (bimonthly period) and Region (southern versus northern OR), and there were no interaction terms.  

The annual index values were derived as the product of two components: predicted values for the probability of catching a black rockfish during a trip, and predicted values for the number of black rockfish caught by an angler per hour of fishing, given that at least one black rockfish was caught.  This CPUE index for Oregon has a high amount of inter-annual variation, particularly in the early part of the time-series.  The index shows a fairly steady upward trend starting from 1987.


##### ORBS Dockside CPUE for Oregon, 2001 to 2014

The ORBS data series for most years does not include full species composition information, and therefore the analysis of these data was restricted to the years 2001-2014, when species composition of the catch is available.  Further, in order to be certain that the characteristics of a trip were comparable, the analysis was restricted to charter boat trips (37,951 records).  The hourly effort associated with these trips can be confounded with travel time, so the travel time was subtracted from the hours fished.  Travel time for charter boats was calculated as 13 mph multiplied by twice the distance between the port of origin and the reef fished (Table 37).  The adjusted hours were multiplied by the number of anglers, and CPUE is expressed in terms of fish per angler-hour.

The species associated with the charter trips were analyzed for inclusion in a Stephens and MacCall [-@stephens_multispecies_2004] logistic regression analysis; "rare species", those occurring in less than 1% of trips, were excluded from consideration as covariates in the analysis.  The regression was run and 21,999 trips predicted to have a likelihood of catching black rockfish above a threshold value of 0.36 were selected as the basis for an index developed in a delta-GLM analysis. Coefficients for predictive species in the analysis are provided in Figure 91.

To develop a standardized CPUE index from the ORBS series, the selected CPUE observations (aggregated catch over aggregated effort) were fitted with a gamma model with main effects for Year, Month, Port, MarBagLim, GF_OpenDepth and ReefFished, with no interactions.  

Model selection based on AIC was used to choose the model with the most support within error distributions (Table 36). AIC was not used to choose between error distributions for the positive catches. This was instead done using quantile-quantile plots (Figure 92 and Figure 93). The full model with lognormal distribution was chosen (Figure 93) and a bootstrap analysis (N=500) was used to estimate the standard errors and CVs of the year effects (Figure 94).
