## Fishery-Independent Data

### Abundance Indices

#### Tagging Study Estimates of Abundance off Newport, OR, 2002 to 2013

Details of the tagging study are available in Krutzikowsky et al. [-@Krutzikowksy_etal_2019] and the implementation in the last stock assessment in Cope et al. [-@cope_assessments_2016]. Briefly, in a study that started in 2002 and concluded in 2014, the ODFW used Passive Integrated Transponder (PIT) tags to mark 2,500 to 4,000 black rockfish annually off Newport, OR.  Marked fish were recovered from recreational fishery landings, with sampling focused on the charter vessel fleet.  Approximately 80% of the annual landings were sampled for marked fish, resulting in the recovery of 3,263 marked fish to date.  

The multi-stage mark-recovery model used to estimate annual survival and recovery rates for the black rockfish population off Newport was similar to "Model 0", as described in Brownie et al. (1985), except that the recovery  rates after the initial year at liberty were held constant.  This particular tagging model configuration was selected because it provided a better AIC score than other models that were evaluated.  It allows direct (first-year) recovery rates to differ from recovery rates of previously marked cohorts, which appeared to be the case in the black rockfish mark-recovery data.  Model 0 parameters were then used to calculate annual exploitation rates, which were then applied to the annual landings to estimate annual abundance.

The basic approach is to estimate the numbers of fish from the equation $N_y= C_y/u_y$, where $C_y$ is the catch (in numbers of fish) in yeary, $N_y$ is the population abundance at the start of the year, and $u_y$ is the exploitation rate.  As in Cope et al. [-@cope_assessments_2016], $u_y$ can be estimated from the ratio of the estimated recovery rate ($\hat{f_y}$) times $C_y$ divided by the number of fish sampled for marks ($cs_y$).  The $C_y$ appearing in the numerator of the equation for $N_y$ cancels with the $C_y$ in the numerator of the equation for $\hat{u_y}$, leaving as the following estimator for  $\hat{N_y}=cs_y/\hat{u_y}$.  Note that $cs_y$ is the number of fish checked for marks, which is known without error in this study.  Approximate estimates of variance for the $\hat{N_y}$ values were derived from the delta method.

$var[\hat{N_y}] \approx [(cs_y)^2/(\hat{f_y})^4]*var[\hat{f_y}]$

##### Spatial Coverage of the Oregon Tagging Study off Newport

One feature of the Oregon assessment model that is somewhat unique is the use of a prior probability distribution for the catchability parameter associated with the tagging study estimates of abundance of exploitable black rockfish off Newport.   The analysis of habitat area coupled with CPUE fish densities indicates that on average 12.7% of the exploitable portion of the black rockfish population off Oregon reside in the waters off Newport.  The lognormal prior distribution was assumed to have a standard deviation of 0.5, which is more than double the between-port variability calculated from the available CPUE data (CV=0.157).  Although trip-level variability in CPUE is typically much larger than 50%, most of the variation in CPUE is due to variability in catchability rather variability in the abundance of the fish. A history of how this prior was established is available in Cope et al. [-@cope_assessments_2016].


#### Nearshore Acoustic-Visual Survey 

Oregon conducted the first statewide combined acoustic-visual survey of nearshore semi-pelagic rockfish in 2021 [@Rasmuson_etal_SSC_2022]. Background details on survey design, data processing, and analyses can be found Rasmuson et al. [-@Rasmuson_etl_untrawlable_2022] and Rasmuson et al. [-@Rasmuson_etl_hydrovideo_2022], including an independent validation of survey methodology (i.e., test area population estimates from the combined acoustic-visual survey were similar to estimates from the overlapping Black Rockfish pit tagging experiment [@Krutzikowksy_etal_2019]). A brief overview of the survey design and the analysis of acoustic data are provided below.

Survey sampling was designed using a systematic sampling layout with parallel transects. Parallel (perpendicular to the north south axis) transects were evenly spaced in Oregon, starting from the Washington border in the north extending to the California border in the south, after random selection of the location for the most northerly transect. Transects were identified as “full” (spaced every 15 km and extending from the 80 m contour shoreward to the surf zone, ~0 m contour) and “rock” transects (spaced every 1 km where “hard” bottom habitat had previously been identified; see @Rasmuson_etal_SSC_2022). The length of each rock transect was equal to the east to west length of each hard habitat cluster plus a 0.5 km buffer applied around the cluster. 

The primary survey vessel was the RV Pacific Surveyor, a 17 m retired commercial fishing vessel converted for research purposes. The secondary vessel, used for shallow water applications, was the RV Arima, a 4.9 m recreational fishing vessel converted for nearshore research in depths shallower than the primary vessel could achieve. Acoustic data were collected using two downward-facing, pole-mounted transducers (BioSonics DT-X split beam Scientific Echosounders: 38 and 201 kHz). Acoustic data were informed using video collected with the Benthically Anchored Suspended Stereo Camera (BASSCam). Video deployment locations were selected in situ by the scientist monitoring the acoustic data in real-time. Twice daily hook and line sampling was also conducted. 

A linked [Online Map](https://www.arcgis.com/apps/mapviewer/index.html?webmap=49e8f3a8079448c29a21d4384d2b50dd) of the survey is available showing locations of all sampling events. A total of 595 acoustic transects were conducted and paired with 496 video drops and 48 fishing stations from 1 August to 9 September 2001. A total of 35,839 fish were identified in the video and 869 fish captured using hook and line. Acoustic target-strength to length conversions were conducted using an aggregate of all video data from the survey. Video drops conducted >50 m from acoustically observed fish were used to predict how many fish were missed by the acoustics. Fish counts were converted to biomass using the length-weight relationship from the hook and line data.

Acoustic data were analyzed using both echo integration and echo counting. Echo integration conversions were done using a combination of target-strength length relationships from the literature (following recommendations from the PFMC Science and Statistical Committee, SSC, review). Acoustic data within 1 m of the bottom (acoustic exclusion zone) were corrected for using data from above the deadzone. Schools of fish were observed over rocky habitats at all of the major nearshore reefs. Additional small patch reefs were also observed interspersed throughout the survey area.

A simple design-based population abundance estimate was generated by averaging the echo integration density of the acoustics in each habitat type (rock, gravel and sand) and multiplying it by the total area of each of those habitat types in three area-based strata (North, Central, and South) spanning the Oregon coast from the Washington border to the California border. Biomass in each area was then calculated by multiplying the estimated abundance by the proportion of fish in each 1 cm bin length class and then converting those length bins to weight using the length to weight relationship obtained from the hook and line data. After summing by region, the result is an independent estimate of coastwide abundance (and biomass) in Oregon waters in 2021. The coefficient of variation of the biomass estimate was also calculated, and it was used to generate the standard error for the assumed lognormal error structure of this data when integrated into candidate stock assessment models. 

#### Marine Reserves Hook and Line Survey 

The Marine Reserves program at ODFW monitors Oregon’s marine reserves. A standardized hook and line survey, modeled after the California marine reserves survey, collects drift-level catch and biological data in both the marine reserves and nearby comparison areas. There are four marine reserve sites (Redfish Rocks, Cape Perpetua, Cascade Head, and Cape Falcon) that span Oregon’s coastline where the hook and line survey is a suitable tool for monitoring. These comparison areas are pre-selected areas with similar bathymetry and habitat characteristics as the reserve but are open to fishing. Each reserve has as least one comparison area, but several have more than one that are monitored regularly along with the reserve. A 500-meter square grid overlaid on the area defines the sampling units or cells. Cells are randomly selected within a marine reserve or comparison area for each sampling event.  Three replicate drifts are executed in each cell. The specific location of the drifts within the cell is selected by the captain. Data are aggregated to the cell-day level and subsequently aggregated to counts of fish per cell-day as the metric for CPUE. Sampling occurs in the spring and late summer/fall seasons. Over time, cells without appropriate habitat for the focus species, mainly groundfish, have been removed from the selection procedures, and those presented in this dataset include only those that are currently “active”.  The number of cells sampled in a day can vary slightly and range from three to five. Sampling was not conducted in 2020 or 2021 due to the COVID-19 pandemic and this survey’s reliance on paid volunteers. 

The dataset contains information on catch by species (number of fish), effort (angler hours), reserve site, area of sampling, treatment (reserve or comparison area), and date of sampling. Additional information that are available include proportion of rock habitat at the cell-level, water temperature, and the average drift depth, though these data are not available for the entire dataset. Average depth (fm) was binned to 10-fm bins (0 – 50fm), and those shallower than 10fm were excluded to a small sample size. April – June was aggregated to a spring season and August - October to a fall season. `r spp` are commonly encountered in this survey (Table \@ref(tab:percent_pos_MRHnL). 

Covariates evaluated included year, month (or season), site, treatment (reserve or comparison area), and depth bin. A negative binomial model was fit to the cell-day-level data (catch in numbers of `r spp` with a log offset for angler hours). Two full model series were considered, one with all the potential covariates with month and one with season. For the series with month, the full model was selected as the best fit model by AIC, but month was almost non-significant. For the series with season, the full model was again selected as the best fit by AIC (Table \@ref(tab:model_selection_MRHnL). When fit via MLE using the sdmTMB R package (version 0.3.0), acceptable diagnostics were achieved for both full models.  However, the error around the point estimates was reduced with the season covariate and ultimately, this was the model selected to be used in the reference model. Previous assessments for nearshore species have explored the use of this survey as a raw index of abundance (@taylor_status_2021, @wetzel_status_2021, @langseth_status_2021, @ cope_assessing_2019) but to date, this index has not been a part of a reference model. Length compositions from this survey are also included.
 


