## Environmental and Ecosystem Data

This stock assessment does not explicitly incorporate trophic interactions, habitat factors or environmental factors into the assessment model. More predation, diet and habitat work, and mechanistic linkages to environmental conditions would be needed to incorporate these elements into the stock assessment and should remain a priority. McClure et al. [-@mcclure_vulnerability_2023] report the climate vulnerability for several west coast groundfishes, including `r spp`. `r spp` demonstrated both high biological sensitivity and high climate exposure risk, to give it an overall high vulnerability score to climate change. This result should also be considered with the fact that, like many rockfishes, periods of low productivity is not unusual to `r spp` and their extended longevity (though admittedly this seems shorter than previously believed and should be reconsidered) has historically allowed them to wait for advantageous productivity periods. In 2021, Oregon's nearshore experienced an extended hypoxic event with some waters becoming fully anoxic [@Rasmuson_etal_SSC_2022]. These events undoubtedly influence the population. Additional stressors such as fishing and climate change that possibly truncate longevity could bring significant challenges to population sustainability. Regardless, no environmental or ecosystem data are directly incorporated into the stock assessment model.
  
## Data Considered but Not Included
  
Special projects data for `r spp` were reviewed but ultimately, with the large number of commercial and recreational samples available under standard sampling protocols, these data were not used in the reference model. There were also multiple sources of fishery-independent information that ODFW has provided to assessments in recent years as ancillary data that were considered. These included ROV survey data, video lander survey data and the Marine Reserves longline survey data. ODFW ROV data were reviewed by an SSC methodology review in 2020 (see PFMC September 2020 briefing book; Agenda Item D.4 Attachment 1) and used to independently estimate population size for Quillback Rockfish in Oregon (@langseth_status_2021). Video lander data from multiple projects was recertly summarized by Marine Resources Program staff (@rasmuson_nine_2020). These data were used to develop density estimates and independent abudance estimates for the most recent assessments for both Quillback Rockfish (@langseth_status_2021) and Lingcod (@taylor_status_2021). These two datasets were not included, as they were not designed specifically to survey `r spp` and the ODFW Nearshore Acoustic-Visual survey was regarded as a stronger estimate of the scale of the `r spp` population scale without the major caveats that come with using the ROV or lander data. Finally, the Marine Reserves longline survey data collected in Oregon's marine reserves were available from 2015 - 2019. While `r spp` are encountered in this survey, samples sizes are lower than the Hook and Line survey and the gear type is not ideal for `r spp`. 

ODFW and Oregon State University have collaborated on juvenile fish monitoring using SMRUF devices in Oregon's Otter Rock Marine Reserve from 2013 to the present. SMURFs are standardized sampling units that collect newly-settled juvenile fishes. These are monitored regularly during during the settlement season (May - September) and juveniles are collected for genetic identification and measured. An index of mean settlement rate of juvenile `r spp` was provided to this assessment. However, the intra-annual standard deviations were extreme (Figure \ref{fig:index1_cpuedata_SMURF}, given the limited samples, and the use of these data as an index of recruitment was explored as a sensitivity. 
