## Characterizing uncertainty
### Sensitivity Analyses
Sensitivity analyses were conducted to evaluate model sensitivity to alternative data treatment and model specifications.

#### Data treatment sensitivities
Data treatments explored were as follows:

- Treatment of absolute abundance catchability (q) 
	1. Acoustic visual survey q = 1, CV = 0.0001
  	2. Acoustic visual survey q Estimated, CV = 0.0001
  	3. Acoustic visual survey q = 1, CV = 0.45
  	4. Acoustic visual survey q estimated, CV = 0.45
  	5. Tag survey q = to 2015 value (0.25)
  	6. Tag survey q = to 2015 value (0.25), but extra variance estimated

- Remove abundance index series 
	7. No Acoustic visual
  	8. No tagging index
  	9. No non-trawl index
  	10. No ORBS index
  	11. No MRFSS index
  	12. No MPA index
	13. Add SMURFs index 

- Data weighting
  	14. No data-weighting
  	15. Dirichlet data-weighting
  	16. McAllister-Ianelli data weighting


Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in Table \ref{tab:data_sensis}. Derived quantities relative to the reference model are provided in Figure \ref{fig:sensi-data-RE}. Time series of spawning output and relative spawning output are shown in Figures \ref{fig:sensi-data-ssb} and \ref{fig:sensi-data-depl}.

Deterministic length-based (with or without catches) models with fixed life history values view the stock scale and status to be below that of the reference model, though above the limit reference point. Bringing in the age data, while still fixing life history and not estimating recruitment, significantly raises the stock scale to above the reference model, though the stock status is similar to the reference model. Introduction of the index made little difference to the relative stock status. Estimating the life history values, even without estimating recruitment, brought the scale back in line with the reference model. The other data treatments, including data weighting options, did very little to change the results from the reference model.


#### Model specification sensitivities
Model specifications looked at the estimation of indiviual and combinations of life history parameters, the estimation of recruitment, and the treatment of fecundity and selectivity. All scenarios match the reference model specifications in all other aspects unless otherwise stated.

- Life history estimation

	- Natural mortality ($M$)
		1. Use 2015 $M$ values 
		2. Lorenzen age varying $M$
		3. Estimate $M$

	- Growth parameters
	 	4. Fix all growth parameters to external values, estimate $M$
		5. Fix all growth parameters to external values
	 	6. Estimate $L_min$
	 	7. Estimate $CV_{young}$ and $CV_{old}$

	- Reproductive Biology
	 	8. Use biological maturity ogive
	 	9. Use functional maturity ogive
	 	10. Fecundity proportional to weight

	- Recruitment estimation
	 	11. No recruitment estimation
	 	12. Estimate recruitment for all years in the model

 Miscellaneous
	13. Estimate logistic selectivity for all fleets
	
Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in Tables \ref{tab:modspec_LH_sensis} and \ref{tab:modspec_RecMisc_sensis}. Derived quantities relative to the reference model are provided in Figure \ref{fig:sensi-modspec-RE}. Time series of spawning output and relative spawning output are shown in Figures \ref{fig:sensi-modspec-ssb} and \ref{fig:sensi-modspec-depl}.

Fixing $M$ to the higher prior mean value while estimating $L_{\infty}$ raised both the beginning and ending stock scale and overall ending year relative stock status. Fixing growth but estimating $M$ dropped stock scale, but preserved the stock status. Allowing either $L_{\infty}$ or $k$ to be estimated increased both stock scale and status. Fixing the life history parameters except for female $L_{\infty}$ also raised stock scale and status, though estiamating males $L_{\infty}$ made little difference to model results. Further investigation of the affects of life history values are provided in the likelihood profiles (next section).

Fixing recruitment dropped the scale and status of the stock a little, fixing life history values again increased those derived outputs. Recruitment estimation (assuming $\sigma_R$ = 0.6) was not sensitive to a range of $\sigma_R$ values or estimation of all years of recruitment. While the truncated time series of recruitment can be considered parsimonious, the addition of estimating all recruitment years adds additional uncertainty to the stock status measure earlier in the time series.

The remaining model specifications did little to change the reference model results. Estimating dome-shaped selectivity after 2003 for the recreational fishery (based on the possibility that fishing restriction in part of the year could possibly limit access to bigger individuals) does result in dome-shaped selectivity for the recreational fishery, it provides only a slighly better fit (based on AIC) to the data and does not change the scale or status of the stock. An even better fit to the data is achieved if 2001 (not coinciding with management changes), though again the derived quantities of scale and status do not change. The improved fits are not sufficient evidence that a selectivity block is needed, though whether and where blocks may be most appropriate is worth future consideration.

Overall, there were no model specification sensitivity scenarios that caused the population to drop significantly below the reference model estimate of stock status, only above. When stock scale changed from the reference model, unfished and current stock size usually varied in the same direction, with current stock size changing more, leading to increases in the relative stocks status. 


### Likelihood Profiles

Likelihood profiles were conducted for the acoustic-visual survey catchability (q) in natural log-space (ln($q$)), steepness ($h$), and female and male natural mortality ($M$) varying together with a constant ratio matching the reference model (0.19/0.17, female and male values respectively). Likelihood profiles were conducted by fixing the featured parameter(s) at specific values across a range of values and estimating all remaining parameters. A likelihood profile offers insight into model sensitivity to changing model parameter values, while providing an additional way to describe uncertainty in the parameter by indentifying the range of parameters within 1.96 likelihood units of the reference model.

The profile on the assumption of the acoustic-visual survey catchaility demonstrates the expected scaling up and down of the population with the decrease and increase of the catchability, respectively (Figure \ref{fig:sAVq-profile}). The change in the current spawning output is steeper than the initial spawning output, leading to a steep decline in relative biomass as ln($q$) gets larger. As the ln($q$) approaches 1.5, the stock approaches the overfished limit reference point. The most supported value of the ln($q$) is found near 1.17 with a very tight support interval. The most prominent length data (in samples and associated fisheries) support larger ln($q$) values, while age compositions support smaller ln($q$) values near the value used in the reference model (Figure \ref{fig:AVq-profile-components}). The less informed survey indices support larger ln($q$) values on the strength of the best fit index (non-trawl CPUE index).

The steepness profile showed little information content for this parameter (Figure \ref{fig:steepness-profile}) as the best fit value went towards the bound of 1. Changing steepness mostly changed the estimate of initial stock size, with a higher initial stock size needed to make up for the lower recruitment compensation. Overall, the relative stock size changed little across a large range of steepness values. The biological compositions pushed the steepness to the highest value, whereas the index data indicated a mixed signal for the lowest and highest steepness values (Figure \ref{fig:steepness-profile-components}).
 
The combined profile that varies female and male $M$ while maintaining the reference model offset demonstrated what had be seen in the model development, that when freely estimated, the model wants natural mortality values to be unreasonably high (Figure \ref{fig:M-multiprofile-combo}). Given the highly constrained model specification (i.e., a fix q on a survey), the range of reasonable natural mortality values adjust the scale of the population in order to match the value fixed in 2021. Similar to the steepness profile, the lower natural mortality values lead to lower productivity, and thus the need for a higher initial biomass, which changes quicker than the current, more pinned down, current biomass value. While the scale does change substantially, the current relative stock status is fairly stable and always above the target level.


### Retrospective Analysis

A ten-year retrospective analysis was conducted by running the model and sequentially removing one year of data up through minus 10 years. Retrospective spawning output (Figure \ref{fig:retro-ssb}) and relatives stock status (Figure \ref{fig:retro-depl}) estimates show a large shift away from a growing population once the acoustic-visual survey is removed from the population. The scale shifts downward and the population status show a declining population at or below the unfished level. This shows the weight of the treatment choice in the acoustic survey, as well as the more recent data that confirm a recent recruitment.


\begin{longtable}[t]{llll}
\caption{\label{tab:RetroMohnsrho}The magnitude of retrospective pattern (Mohn's rho; Mohn, 1999) given the removal of ten years of data for fishing intensity (\emph{F}), fraction unfished (Figure \ref{fig:retro-depl}),  recruitment, and spawning stock biomass (\emph{SSB}; Figure \ref{fig:retro-ssb}). Columns are a derivation of Mohn's rho (Hurtado-Ferro et al. 2015) used by the Alaska Fisheries Science Center (AFSC), as originally described in Mohn (1999), and a derivation of Mohn's rho (Woods Hole Mohn's rho; Legault 2009) used by the Northeast Fisheries Science Center (NEFSC).}\\
\toprule
Quantity & AFSC & Mohn & NEFSC\\
\midrule
\emph{F} & 1.733824 & 17.33824 & 4.591969\\
Fraction unfished & -0.4494829 & -4.494829 & -0.4856366\\
Recruitment & -0.5536441 & -5.536441 & -2.727355\\
\emph{SSB} & -0.6081382 & -6.081382 & -3.459641\\
\bottomrule
\end{longtable}

### Unresolved Problems and Major Uncertainties

The biggest uncertainty and unresolved conflict is trying to reconcile the signal in the biological data (which want a lower population size and status) versus the acoustic and tag surveys (which want high stock sizes and status). This is the major issue the current assessment is confronting. Another acoustic-visual survey data point could help resolve how much uncertainty there is in the estimate. The lack of contrast in the biological data, despite large sample sizes, is another barrier to interpreting the current conditions, though given models using only biological data, the signal seems clear that the population could be at a lower stock status. 